CoMOT: true
CoMOT_loss_ce: false
FN_det_query_loss_coef: 2.0
aux_loss: true
avg_attn_weight_maps: true
backbone: resnet18
backprop_prev_frame: true
batch_size: 2
bbox_loss_coef: 5.0
clip_max_norm: 0.1
cls_loss_coef: 4.0
cls_threshold: 0.5
crop: false
data_dir: C:\Users\charvin\SynologyDrive\Data\DetecDivProjects\anais\bud4\classification\celltracktr_5\trainingdataset
data_viz: false
dataset: moma
debug: false
dec_layers: 4
dec_n_points: 4
deformable: true
device: cuda
dice_loss_coef: 5.0
dilation: false
dim_feedforward: 512
display_all: false
dist_url: env://
div_loss_coef: 5.0
dn_enc: false
dn_enc_l1: 0.3
dn_enc_l2: 0.15
dn_object: false
dn_object_FPs: false
dn_object_coef: 1.0
dn_object_l1: 0.3
dn_object_l2: 0.15
dn_track: true
dn_track_coef: 1.0
dn_track_group: true
dn_track_l1: 0.2
dn_track_l2: 0.1
dropout: 0.1
enc_FN: 1
enc_layers: 4
enc_masks: true
enc_n_points: 4
eos_coef: 0.1
epochs: 12
eval_only: false
flex_div: false
flex_div_loss_coef: 0.0
focal_alpha: 0.25
focal_gamma: 2
focal_loss: true
freeze_backbone: false
freeze_backbone_and_encoder: false
freeze_detr: false
giou_loss_coef: 2.0
hidden_dim: 144
hooks: false
init_boxes_from_masks: true
init_enc_queries_embeddings: false
iou_threshold: 0.5
load_mask_head_from_model: null
loss_coef: 1.0
lr: 0.0002
lr_backbone: 2.0e-05
lr_backbone_names:
- backbone.0
lr_drop: 11
lr_linear_proj_mult: 0.1
lr_linear_proj_names:
- reference_points
- sampling_offsets
lr_track: 0.0001
mask_dim: 288
mask_loss_coef: 5.0
mask_weight_all_cells_coef: 10.0
mask_weight_target_cell_coef: 2.0
masks: true
match_masks: true
multi_frame_attention: false
multi_frame_attention_separate_encoder: false
nheads: 8
num_OD_layers: 1
num_feature_levels: 3
num_plots: 10
num_points: 10000
num_queries: 30
num_workers: 0
object_queies_loss_coef: 1.0
output_dir: C:\Users\charvin\SynologyDrive\Data\DetecDivProjects\anais\bud4\classification\celltracktr_5\results\moma
overflow_boxes: true
overwrite_lr_scheduler: false
overwrite_lrs: false
pos_wei_loss_coef: 5.0
position_embedding: sine
pre_norm: false
refine_div_track_queries: false
refine_object_queries: true
refine_track_queries: true
resume: ''
resume_optim: true
resume_shift_neuron: false
return_intermediate_masks: true
save_model_interval: false
seed: 42
set_cost_bbox: 5.0
set_cost_class: 4.0
set_cost_dice: 5.0
set_cost_giou: 2.0
set_cost_mask: 5.0
share_bbox_layers: false
shift: false
start_epoch: 1
target_size: (256,32)
tgt_noise: 0.1
touching_edge_loss_coef: 0.2
track_div_loss_coef: 2.0
tracking: true
two_stage: true
use_dab: true
use_div_box_as_ref_pts: true
use_img_for_mask: true
use_prev_prev_frame: true
val_interval: 5
weight_decay: 0.0001
with_box_refine: true
world_size: 1
